services:
  haproxy:
    image: haproxy:2.9
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "443:443"
      - "8404:8404"
    restart: unless-stopped

  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    command: -conf /Corefile
    volumes:
      - ./coredns/Corefile:/Corefile:ro
      - ./coredns/certs:/certs:ro
    ports:
      - "853:853/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
