services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - coredns
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    restart: unless-stopped

  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    command: -conf /Corefile
    volumes:
      - ./coredns/Corefile:/Corefile:ro
      - ./coredns/certs:/certs:ro
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
    restart: unless-stopped
